# Deployment postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "review"
          - name: POSTGRES_PASSWORD
            value: "review"
          - name: POSTGRES_DB
            value: "review"

---

# Deployment service postgre
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
    type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432

---

# Deployment do review de filmes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
      - name: review
        image: edersnk/review-jornada:v1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings_DefaultConnection
          value: "Host=postgre;Database=review;Username=review;Password=review"
---

# Deployment Service review de filmes

apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  selector:
    app: review
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080


