name: ci-cd
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter codigo do Projeto
        uses: actions/checkout@v4

      - name: Executar testes setupo .net
        uses: xt0rted/setup-dotnet@v1.0.0  
        with:
          dotnet-version: 8.x

      - name: Execução do teste
        working-directory: ./02-review/src/Review-Filmes.Test.Unit
        run: dotnet test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build e push da imagem docker
        uses: docker/build-push-action@v6
        with:
          # Nome  da imagem
          tags: |
            edersnk/review-jornada:v${{ github.run_number }}
            edersnk/review-jornada:latest
          # Contexto
          context: ./02-review/src
          # Docker file
          file: ./02-review/src/Review-Filmes.Web/Dockerfile
          push: true

  cd: 
    needs: ["ci"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter codigo"
      - run: echo "Configurar kubeconfig"
      - run: echo "Executar o apply"
